### ISSUE TITLE
Norm of gradient waveforms > 1

### ISSUE THREAD

**Issue by cf-westin** [jsjol/NOW#27]
The L2 norm for a gradient waveform is sometimes slightly larger than 1 when the optimization is set to "Euclidean" that ensures that the waveform can be rotated. It would be helpful to have the max L2 norm normalized to 1 after optimization. This was noticed when the optimized waveform was loaded into the Bruker free waveform diffusion sequence "dwiWave_Stanv6" developed Matthew Budde. This sequence requires normalized gradient waveforms.

**Comment by jsjol** [comment]
Thanks for the info. I think this can be fixed with a one-liner (shifting the constraint so that it's "norm <= (1-tol)" instead of "norm <= 1"). I'll address this within the coming two weeks.

Btw, if the user resamples the sequence after optimization that might violate the normalization.

**Comment by jsjol** [comment]
Ok, I've found the problem, and it's actually not what I thought. The violation occurs due to the normalization of the gradients that happens when saving to file, here:

https://github.com/jsjol/NOW/blob/ce90710d2a4fe9cd264ba622b5b733714aac4113/NOW_GUI.m#L606-L610 

I'd like to get some input from @filip-szczepankiewicz on how to fix this. It seems that having g_max = 1 and 2-norm=1 are incompatible constraints in general. Perhaps it should switch to match whether the optimization used max-norm or Euclidean norm.

It's also true that the optimization violates the constraints a tiny bit. But this could be controlled, at the cost of longer optimization times, by changing the ConstraintTolerance in OptimOptions. It's hard to get under the hood to see exactly how MATLAB computes the constraint violation, the documentation only reveals that it uses a relative tolerance.

**Comment by filip-szczepankiewicz** [comment]
I have thought about this for a while now, and I keep going back to: what is the responsibility of the optimizer vs the user?

If we ask for the L2-norm, I think it is reasonable for NOW to spit out a waveform that has a maximal L2-norm = g_max. However, when we save/export the waveform, we use a **completely** different format, informed mainly by how I implemented the FWF pulse sequence.

Therefore, i think we should keep the optimizer as is (accepting the current overshoot due to tolerance), because NOW is actually doing what we asked from it.

The solution, if any, should be in the 'export to txt' step. The problem with this is that the 'fix' must follow some arbitrary set of rules imposed by the intended scanner/pulse sequence, which we cannot (should not) predict. Therefore, I am leaning towards a neutral output format (eg the current one), such that the user takes care of any necessary checks and fixes before final use.

In this particular case, checking and re-scaling the waveform is trivial, and most users of these kinds of tools are capable enough to do this kind of thing.

I can imagine fixes that are specific to max and L2-norms... and different b-tensor shapes... but I fear that would lead to some serious over-engineering.

**Comment by jsjol** [comment]
Agreed, closing.
